name: bbot
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pyqt
  - pip:
    - atomicwrites==1.4.1
    - attrs==22.1.0
    - bcrypt==3.2.2
    - certifi==2022.6.15
    - cffi==1.15.1
    - charset-normalizer==2.1.0
    - colorama==0.4.5
    - contextlib2==21.6.0
    - cryptography==37.0.4
    - et-xmlfile==1.1.0
    - execnet==1.9.0
    - idna==3.3
    - iniconfig==1.1.1
    - mock==4.0.3
    - numpy==1.23.1
    - openpyxl==3.0.10
    - packaging==21.3
    - paho-mqtt==1.6.1
    - pandas==1.4.3
    - paramiko==2.11.0
    - path==16.4.0
    - path.py==12.5.0
    - pathlib2==2.3.7.post1
    - pluggy==1.0.0
    - py==1.11.0
    - pycparser==2.21
    - PyNaCl==1.5.0
    - pyparsing==3.0.9
    - pytest==7.1.2
    - pytest-shutil==1.7.0
    - python-dateutil==2.8.2
    - python-dotenv==0.20.0
    - pytz==2022.1
    - requests==2.28.1
    - RPi.GPIO
    - six==1.16.0
    - socketIO-client==0.7.2
    - termcolor==1.1.0
    - tomli==2.0.1
    - urllib3==1.26.11
    
    - websocket-client==1.3.3
    - depthai==2.17.3.0
    - opencv-python
