name: bb_env
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2022.07.19=haa95532_0
  - certifi=2022.6.15=py310haa95532_0
  - libffi=3.4.2=hd77b12b_4
  - openssl=1.1.1q=h2bbff1b_0
  - pip=22.1.2=py310haa95532_0
  - python=3.10.4=hbb2ffb3_0
  - setuptools=63.4.1=py310haa95532_0
  - sqlite=3.39.2=h2bbff1b_0
  - tk=8.6.12=h2bbff1b_0
  - tzdata=2022a=hda174b7_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.37.1=pyhd3eb1b0_0
  - wincertstore=0.2=py310haa95532_2
  - xz=5.2.5=h8cc25b3_1
  - zlib=1.2.12=h8cc25b3_2
  - pip:
    - bcrypt==4.0.0
    - blobconverter==1.3.0
    - boto3==1.24.60
    - botocore==1.27.60
    - cffi==1.15.1
    - charset-normalizer==2.0.12
    - cryptography==37.0.4
    - depthai==2.17.3.0
    - et-xmlfile==1.1.0
    - ffmpy3==0.2.4
    - idna==3.3
    - jmespath==1.0.1
    - lz4==4.0.2
    - mcap==0.0.14
    - mcap-ros1-support==0.0.8
    - numpy==1.23.2
    - opencv-contrib-python==4.5.4.58
    - opencv-python==4.5.4.58
    - openpyxl==3.0.10
    - paho-mqtt==1.6.1
    - pandas==1.4.3
    - paramiko==2.11.0
    - pycparser==2.21
    - pynacl==1.5.0
    - pyqt5==5.15.5
    - pyqt5-qt5==5.15.2
    - pyqt5-sip==12.11.0
    - pyqt6==6.3.1
    - pyqt6-qt6==6.3.1
    - pyqt6-sip==13.4.0
    - python-dateutil==2.8.2
    - python-dotenv==0.20.0
    - pytube==12.1.0
    - pyturbojpeg==1.6.4
    - pytz==2022.2.1
    - pyusb==1.2.1
    - pyyaml==6.0
    - requests==2.26.0
    - rosbags==0.9.11
    - ruamel-yaml==0.17.21
    - ruamel-yaml-clib==0.2.6
    - s3transfer==0.6.0
    - sentry-sdk==1.5.1
    - six==1.16.0
    - urllib3==1.26.12
    - zstandard==0.18.0
